[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "2.1.17"
solana-client = "2.1.17"
spl-token = { version = "4.0", features = ["no-entrypoint"] }

dotenvy = "0.15"
serde_json = "1.0"